spring.application.name=Attendance-Managment-System
spring.datasource.url=jdbc:mysql://localhost:3306/Attendance_Managment_System?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Abhirat@87654321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=trues
server.port=0