
spring.application.name=Notes-Managment-System
spring.datasource.url=jdbc:mysql://localhost:3306/Notes_Managment_System
spring.datasource.username=root
spring.datasource.password=Abhirat@87654321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088